FROM debian:buster
# ARG BASE_CONTAINER=jupyter/minimal-notebook
# FROM $BASE_CONTAINER

ENV SCALA_VERSION=2.12.8
ENV ALMOND_VERSION=0.6.0
ENV JAVA_VERSION=12
ENV RUBY_VERSION=2.6.4

EXPOSE 8888

ARG REPO_ADDR=http://deb.debian.org

# RUN sed -i 's@${REPO_ADDR}/@http://mirror.kakao.com/@g' /etc/apt/sources.list
# RUN sed -i 's@${REPO_ADDR}/@http://mirror.kakao.com/@g' /etc/apt/sources.list
# RUN sed -i 's@http://cdn-fastly.deb.debian.org/@http://mirror.kakao.com/@g' /etc/apt/sources.list
# RUN sed -i 's@http://cdn-fastly.deb.debian.org/@http://mirror.kakao.com/@g' /etc/apt/sources.list
# RUN sed -i 's@http://archive.ubuntu.com/@http://mirror.kakao.com/@g' /etc/apt/sources.list
# RUN sed -i 's@http://security.ubuntu.com/@http://mirror.kakao.com/@g' /etc/apt/sources.list
RUN apt-get update -qq && apt-get -y upgrade

RUN apt-get -y install sudo tree vim build-essential git zip unzip curl
# RUN apt-get clean

RUN apt-get install -y python3 python3-pip &&\
    apt-get install -y libzmq3-dev &&\
    pip3 install --upgrade pip && \
    pip3 install jupyter

RUN pip install --upgrade "ipython[all]"
RUN ipython console --kernel scala211

# JVM
RUN curl -s "https://get.sdkman.io" | bash &&\
    source "$HOME/.sdkman/bin/sdkman-init.sh"

RUN sdk i java 12.0.2-zulu &&\
    sdk i gradle &&\
    sdk i maven &&\
    sdk i scala ${SCALA_VERSION} &&\
    sdk i sbt &&\
    sdk i kotlin &&\
    sdk i kscript &&\
    sdk i groovy &&\
    sdk i sbt &&\
    sdk i leiningen &&\
    sdk i ceylon

# SCALA
RUN curl -Lo /usr/local/bin/coursier https://git.io/coursier-cli &&\
    chmod +x /usr/local/bin/coursier &&\
    coursier bootstrap \
    -r jitpack \
    -i user -I user:sh.almond:scala-kernel-api_$SCALA_VERSION:$ALMOND_VERSION \
    sh.almond:scala-kernel_$SCALA_VERSION:$ALMOND_VERSION \
    --sources --default=true \
    -o almond &&\
    ./almond --install
    # rm -f almond


# RUBY
# RUN apt-get install -y libssl-dev libreadline-dev zlib1g-dev \
#     libffi-dev make \
#     git libzmq3-dev autoconf pkg-config libczmq-dev libczmq4
RUN apt-get install -y libtool libffi-dev make \
    libzmq3-dev libczmq-dev
RUN git clone https://github.com/rbenv/rbenv.git ~/.rbenv &&\
    git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build &&\
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc &&\
    echo 'eval "$(rbenv init -)"' >> ~/.bashrc &&\
    rbenv install 2.6.4 &&\
    rbenv global 2.6.4 &&\
    gem install iruby cztop ffi-rzmq &&\
    iruby register --force

# R
RUN apt-get install -y --no-install-recommends \
    fonts-dejavu unixodbc unixodbc-dev r-cran-rodbc gfortran gcc 

# R packages
RUN conda install --quiet --yes \
    'r-base=3.6.1' \
    'r-caret=6.0*' \
    'r-crayon=1.3*' \
    'r-devtools=2.0*' \
    'r-forecast=8.7*' \
    'r-hexbin=1.27*' \
    'r-htmltools=0.3*' \
    'r-htmlwidgets=1.3*' \
    'r-irkernel=1.0*' \
    'r-nycflights13=1.0*' \
    'r-plyr=1.8*' \
    'r-randomforest=4.6*' \
    'r-rcurl=1.95*' \
    'r-reshape2=1.4*' \
    'r-rmarkdown=1.14*' \
    'r-rodbc=1.3*' \
    'r-rsqlite=2.1*' \
    'r-shiny=1.3*' \
    'r-sparklyr=1.0*' \
    'r-tidyverse=1.2*' \
    'unixodbc=2.3.*' \
    && \
    conda clean --all -f -y && \
    fix-permissions $CONDA_DIR

# Install e1071 R package (dependency of the caret R package)
RUN conda install --quiet --yes r-e1071

RUN rm -rf /var/lib/apt/lists/*
CMD ["jupyter", "notebook"]